# Main Site settings *** ENGLISH ***

baseURL = "/"
languageCode = "en"
title = "SENAITE LIMS"
theme = "senaite"
publishDir = "../senaite.github.io"
cleanDestinationDir = "True"

[params]
    name="SENAITE Foundation"
    description = "SENAITE - Next Generation LIMS"
    mailto = "senaite@senaite.com"
    copyright = "SENAITE Foundation."

    # navigation (see partials/navigation.html)
    [params.navbar]

        [[params.navbar.list]]
            title = "SENAITE"
            href = "#main"

        [[params.navbar.list]]
            title = "Features"
            href = "#features"

        [[params.navbar.list]]
            title = "Download"
            href = "#download"

        [[params.navbar.list]]
           title = "Service Providers"
           href = "#providers"

        [[params.navbar.list]]
            title = "Contact"
            href = "#contact"

    [params.providers]

        [[params.providers.list]]
            name = "RIDING BYTES"
            url = "https://www.ridingbytes.com"
            mail = "hello@ridingbytes.com"
            logo = "assets/logos/ridingbytes.png"
            slogan = "Professional Open Source Solutions"
            location = "Germany"

        [[params.providers.list]]
            name = "NARALABS"
            url = "https://naralabs.com"
            mail = "info@naralabs.com"
            logo = "assets/logos/naralabs.png"
            slogan = ""
            location = "Barcelona"

    [params.download]
        pdf = "https://downloads.senaite.com/SENAITE%20VM.pdf"
        vm = "https://downloads.senaite.com/SENAITE%20VM.ova"